version: 2.1

orbs:
  snyk-scan: snyk/snyk@dev:master

jobs:
  build_app:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: npm install -q
      - snyk-scan/scan:
          severity: high
          protect: true
          failOnIssues: false
          monitorOnBuild: true
          targetFile: "package.json"
          # token: "$SNYK_TOKEN"
          # organization: "$SNYK_ORGANIZATION"
          # project: "$SNYK_PROJECT"

  build_img:
    working_directory: ~/my-app
    environment:
      IMAGE_NAME: goof-image
    docker:
        - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - snyk-scan/scan:
          severity: high
          failOnIssues: false
          monitorOnBuild: true
          targetFile: "Dockerfile"
          dockerImageName: $IMAGE_NAME:latest
          # token: "$SNYK_TOKEN"
          # organization: "$SNYK_ORGANIZATION"
          # project: "$SNYK_PROJECT"
workflows:
  version: 2
  build_app_and_img:
    jobs:
      - build_app
      - build_img
