version: 2.1

orbs:
  snyk: snyk/snyk@dev:more-params

jobs:
  build_app:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: npm install -q
      - snyk/scan:
          token-variable: SNYK_TOKEN
          organization-variable: SNYK_ORGANIZATION
          severity: high
          protect: true
          failOnIssues: false
          monitorOnBuild: true
          project: ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app

  build_img:
    working_directory: ~/my-app
    environment:
      IMAGE_NAME: goof-image
    docker:
        - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - snyk/scan:
          severity: high
          failOnIssues: false
          monitorOnBuild: true
          token-variable: SNYK_TOKEN
          organization-variable: SNYK_ORGANIZATION
          dockerImageName: $IMAGE_NAME:latest
          targetFile: "Dockerfile"
          project: ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app

workflows:
  version: 2
  build_app_and_img:
    jobs:
      - build_app
      - build_img
