Original config.yml file:
version: 2.1

orbs:
    snyk-scan: mikomraz/snyk-scan@dev:0.0.1

jobs:
  build:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: npm install -q
      - snyk-scan/scan:
          token: $SNYK_TOKEN
          severity: high
          failOnIssues: false
          monitorOnBuild: true
          projectName: $SNYK_PROJECT
          organisation: $SNYK_ORGANIZATION
          targetFile: "package.json"