version: 2.1

orbs:
  snyk-scan: mikomraz/snyk-scan@dev:master

jobs:
  build:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: npm install -q
      - snyk-scan/scan:
          severity: high
          failOnIssues: true
          monitorOnBuild: true
          targetFile: "package.json"
          # token: "$SNYK_TOKEN"
          # organization: "$SNYK_ORGANIZATION"
          # project: "$SNYK_PROJECT"